version: "3"

services:
  node:
    image: node:16.14
    build: .
    container_name: cashforce_backend
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./backend:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: db
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
    networks:
      - cashforce_net

  db:
    container_name: cashforce_db
    image: mysql:8.0.23
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - cashforce_net

networks:
  cashforce_net:
    driver: bridge
